spring:
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/clientes_db?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: jardel894

  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    hibernate:
      jdbc: time_zone = TimeZone
    show-sql: true
    format_sql: true

  jackson:
    default-property-inclusion: NON_NULL

